version: "3"
services:
  ruby_rails:
    build:
      context: .
    container_name: cube_ruby_rails
    environment:
      - DD_SERVICE=cube_sample_ruby_rails_datadog
      # send traces to CubeAPM
      - DD_TRACE_AGENT_URL=http://host.docker.internal:3130

      # optional settings
      # - DD_ENV=myenv
      # - DD_VERSION=1.2.3
      # - DD_TAGS=mykey1:myvalue1,mykey2:myvalue2

      # Print Datadog tracer startup logs on screen
      # - DD_TRACE_STARTUP_LOGS=true
      # Enable Datadog tracer debug logging if needed to see detailed logs
      # - DD_TRACE_DEBUG=true
    ports:
      - "9000:9000"
    depends_on:
      - mysql
      - redis
    restart: always

  mysql:
    image: mysql:8.0
    container_name: cube_ruby_rails_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    volumes:
      - cube_ruby_rails_mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine3.18
    container_name: cube_ruby_rails_redis

volumes:
  cube_ruby_rails_mysql:
